name: Update website

on:
  push:
    branches:
      - main
env:
  BASE_URL: /${{ github.event.repository.name }}

permissions:
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BASE_URL: /${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'
          pip-install: '-r requirements.txt'
      - uses: actions/cache@v5
        with:
          path: './_build/execute'
      - name: Run jupyter-book
        run: jupyter-book build --execute --html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_build/html'
  deploy:
    name: Deploy
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
